name: flutter_application
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  http: '>=0.11.3+12'
  simple_animations: ^3.2.0
  supercharged: ^2.1.1
  #网络连接
  connectivity: 3.0.6
  # 持久化存储
  shared_preferences: 2.0.7
  date_format: 2.0.4
  # flutter_markdown: 0.6.10
  flutter_easyrefresh: ^2.2.1
  path_provider: ^2.0.9
  fluttertoast: ^8.0.9
  open_file: 3.2.1
  # permission_handler: 9.2.0
  intl: ^0.17.0
  flukit: ^2.0.0
  # refined_markdown: ^1.2.2
  yaml: ^3.1.0
  json2yaml: ^3.0.0
  provider: ^6.0.2
  # zefyrka: ^1.2.0-dev.1
  zefyr: ^1.0.0-rc.5
  file_picker: ^4.5.1
  # quill_delta: ^2.0.0
  # delta_markdown: ^0.6.0
  filesystem_picker: ^2.0.0
  material_tag_editor: ^0.1.2
  # dotted_border: 2.0.0+2
  flutter_quill: ^4.1.9
  universal_html: ^2.0.8
  flutter_easyloading: ^3.0.3
  animated_search_bar: ^2.2.0
  github: ^9.2.0
  google_fonts: ^2.3.2
  bitsdojo_window: ^0.1.1+1
  logger: ^1.1.0
  watcher: ^1.0.1
  # fluent_ui: ^3.10.0
  # searchable_listview: ^1.5.2
  # searchfield: ^0.6.4
  # search: ^0.3.0
  # markdown_quill: ^0.0.2+1
  # notus_format: ^1.0.3

#  flutter_html: ^2.0.0
#  flutter_tag_layout: ^0.0.3


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_model: ^1.0.0
  # json_serializable: ^5.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/images/
    - assets/images/juejin_logo.png
    - assets/images/bg.png
    - assets/json/categories.json
    - assets/json/articles.json
    - assets/json/article_detail.json
    - assets/json/boil.json


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  # 阿里矢量图标引入
    - family: MyIcons
      fonts:
        - asset: assets/icons/iconfont.ttf
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.otf
        - asset: assets/fonts/NotoSansSC-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansSC-Bold.otf
          weight: 600
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
